[project]
user_env = []
session_timeout = 3600
user_session_timeout = 1296000  # 15 days
cache = false
persist_user_env = false
mask_user_env = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = false
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true
allow_thread_sharing = false

[features.slack]
reaction_on_message_received = false

[features.spontaneous_file_upload]
    enabled = true
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 1000

[features.audio]
    enabled = false
    sample_rate = 24000

[features.mcp]
    enabled = false

[features.mcp.sse]
    enabled = true

[features.mcp.streamable-http]
    enabled = true

[features.mcp.stdio]
    enabled = true
    allowed_executables = [ "npx", "uvx" ]

[UI]
name = "gLLM"
github = 'https://github.com/dylan-000/gLLM'

default_theme = "light"
default_sidebar_state = "open"
cot = 'hidden'
alert_style = "classic"
logo_file_url = ""
default_avatar_file_url = ""

[[UI.header_links]]
    name = ""
    display_name = "Back"
    icon_url = "http://localhost:8001/gllm/logo?theme=dark&"
    url = "https://github.com/dylan-000/gLLM"

[meta]
generated_by = "2.9.2"
